### ISSUE TITLE
After performing "SaveChanges" the response is missing "insertedKeys" array

### ISSUE THREAD

**Issue by zakanych** [ppoliani/breeze-mongoose#1]
![image](https://cloud.githubusercontent.com/assets/9998390/5573216/e7c08492-8fb1-11e4-87ab-6261a856534c.png)

I use the latest 'breezejs' v1.5.2 on the client. The screenshot is taken from the adapter file for MongoDB: breeze.dataService.mongo.js

Is there any possibility to get a working example of an application with CRUD operations that uses breeze-mongoose package?

**Comment by pavlospolianidis** [comment]
I'll try to create a sample CRUD application to show how it works. 

Why are you using breeze.dataService.mongo.js?

**Comment by pavlospolianidis** [comment]
You're welcome, by the way, to add your own sample app.

**Comment by zakanych** [comment]
I was using one of the sample projects from Breeze (http://www.getbreezenow.com/samples/zza) in which author uses "mongodb" library at backend and "breezejs" (with that adapeter) at frontend. I wanted to adapt the application to use mongoose at a backend (and I see that your library helps to overcome the problem of defining the metadata on both backend and frontend). But caught this problem as described above.

**Comment by pavlospolianidis** [comment]
It would be useful if you could share the sample app your're testing.

**Comment by ppoliani** [comment]
I have uploaded an example
https://github.com/ppoliani/breeze-mongoose-example

**Comment by zakanych** [comment]
Thank, you for a good example!
