### ISSUE TITLE
TypeError: Object #<Object> has no method 'serialize'

### ISSUE THREAD

**Issue by zakanych** [ppoliani/breeze-mongoose#2]
![image](https://cloud.githubusercontent.com/assets/9998390/5603494/ff73650a-938f-11e4-9391-b3f8ee703d5b.png)

When trying to call a method "SaveChanges" (specifically update or delete) dbManager loads an entity from MongoDB and calls a method _getBreezeEntityFromDto, passing a dto parameter (an entity loaded from the database), whose "schema">"methods" missing the "serialize" method.

**Comment by ppoliani** [comment]
For the time being, add a serialize method to the Schema of the model in question.

```
modelSchema.method('serialize', function serialize(ret){
     return ret;
});
```

I will try to find the source of the problem.

**Comment by ppoliani** [comment]
Can you tell me the schema that causes this error?

**Comment by zakanych** [comment]
I've defined "Forum" schema for the application:

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var AuthorSchema = {
    name: {type: String, default: '', trim: true},
    timeStamp: {type: Date, default: Date.now}
};

var ForumSchema = new Schema({
    ownerId: Number,
    author: AuthorSchema,
    title: {type: String, default: '', trim: true},
    description: {type: String, default: '', trim: true},
    code: {type: String, default: '', trim: true},
    imageUrl: {type: String, default: '', trim: true},
    moderated: Boolean,
    lastPostAuthor: AuthorSchema,
    importance: Number,
    sortOrder: Number
});

ForumSchema.virtual('id').get(function () {
    return this._id.toHexString();
});

ForumSchema.set('toJSON', {
    virtuals: true
});

module.exports = mongoose.model('Forum', ForumSchema);

**Comment by zakanych** [comment]
I've defined a similar schema as "Article" in your sample application:

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var AuthorSchema = {
    name: {type: String, default: '', trim: true},
    timeStamp: {type: Date, default: Date.now}
};

var ForumSchema = new Schema({
    ownerId: Number,
    author: AuthorSchema,
    title: {type: String, default: '', trim: true},
    description: {type: String, default: '', trim: true},
    code: {type: String, default: '', trim: true},
    imageUrl: {type: String, default: '', trim: true},
    moderated: Boolean,
    lastPostAuthor: AuthorSchema,
    importance: Number,
    sortOrder: Number
});

ForumSchema.virtual('id').get(function () {
     return this._id.toHexString();
});

ForumSchema.set('toJSON', {
    virtuals: true
});

module.exports = mongoose.model('Forum', ForumSchema);
```

Note: the update and delete operations are performed sucessfuly. The error occurs during formation of breeze response to the browser.

**Comment by ppoliani** [comment]
Could you debug and check which model is missing the serialize method?

**Comment by zakanych** [comment]
Any model that is loaded from MongoDB using mongoose library in the application does not have a "serialize" method in its schema definition. When do you expect it to be attached to?
Currently using a mongoose library of version 3.8.21.

**Comment by ppoliani** [comment]
That's interesting; In the example app, I do not explicitly set the serialize method. 

Try to do the following: 

```
 ForumSchema.method('serialize', function serialize(ret){
       return ret;
 });
```

**Comment by ppoliani** [comment]
I will fix this issue later; For the time being look at the previous comment and define a serialize method for all you models. 

I can try to fix this now; but I don't have time to test it

**Comment by ppoliani** [comment]
Can you test this again. I published an updated npm package

**Comment by zakanych** [comment]
Thanks for your changes. The issue is resolved.
