### ISSUE TITLE
Complex type reflection problem

### ISSUE THREAD

**Issue by zakanych** [ppoliani/breeze-mongoose#3]
Once define a complex type in a mongoose schema, it is reflected in the metadate with "defaultResourceName", but should not.

Example:
var ForumSchema = new Schema({
    ownerId: Number,
    author: {
        name: {type: String, default: '', trim: true},
        timeStamp: {type: Date, default: Date.now}
    },
    title: {type: String, default: '', trim: true},
    description: {type: String, default: '', trim: true},
    code: {type: String, default: '', trim: true},
    imageUrl: {type: String, default: '', trim: true},
    moderated: Boolean,
    importance: Number,
    sortOrder: Number
});

Pay attention on "author" property.

Result metadata JSON:
![image](https://cloud.githubusercontent.com/assets/9998390/5660473/56e69e28-9729-11e4-9787-4a012b221f7f.png)

This leads to an exception while parsing the metadata on breeze client script.

**Comment by pavlospolianidis** [comment]
I updated the both the package and the example.

**Comment by ppoliani** [comment]
I updated both the package and the example.

**Comment by zakanych** [comment]
Thanks you.
